os: linux
sudo: required
language: "minimal"
services:
  - docker

jobs:
  include:
    - name: "compile"
      script:
        - chmod 755 scripts/*.sh
        - docker run -v `pwd`:`pwd` -w `pwd` -t rusdevops/bootstrap-cpp scripts/compile.sh
    - name: "checks"
      script:
        - docker run -v `pwd`:`pwd` -w `pwd` rusdevops/bootstrap-cpp scripts/checks.sh
    - name: "coverage"
      script:
        - docker run -t -v $(pwd):/var/builder/ -w /var/builder --entrypoint ./scripts/coverage.sh $DOCKER_IMAGE
    - name: "tests"
      script:
        - docker run -t -v $(pwd):/var/builder/ -w /var/builder --entrypoint ./scripts/tests.sh $DOCKER_IMAGE


notifications:
email: false